name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.6
  - flask
  - boto3
  - numpy
  - pandas
  - CoolProp
  - shapely
  - geopandas
  - matplotlib
  - pydap
  - s3fs
  - fsspec
  - rq
  - reddis